const D={nato:[['A','Alpha'],['B','Bravo'],['C','Charlie'],['D','Delta'],['E','Echo'],['F','Foxtrot'],['G','Golf'],['H','Hotel'],['I','India'],['J','Juliett'],['K','Kilo'],['L','Lima'],['M','Mike'],['N','November'],['O','Oscar'],['P','Papa'],['Q','Quebec'],['R','Romeo'],['S','Sierra'],['T','Tango'],['U','Uniform'],['V','Victor'],['W','Whiskey'],['X','X-ray'],['Y','Yankee'],['Z','Zulu']],deutsch:[['A','Aachen'],['Ä','Umlaut Aachen'],['B','Berlin'],['C','Chemnitz'],['D','Düsseldorf'],['E','Essen'],['F','Frankfurt'],['G','Goslar'],['H','Hamburg'],['I','Ingelheim'],['J','Jena'],['K','Köln'],['L','Leipzig'],['M','München'],['N','Nürnberg'],['O','Offenbach'],['Ö','Umlaut Offenbach'],['P','Potsdam'],['Q','Quickborn'],['R','Rostock'],['S','Salzwedel'],['ß','Eszett'],['T','Tübingen'],['U','Unna'],['Ü','Umlaut Unna'],['V','Völklingen'],['W','Wuppertal'],['X','Xanten'],['Y','Ypsilon'],['Z','Zwickau']]};
const K='funkalphabet-v60';let S=JSON.parse(localStorage.getItem(K)||'null')||{a:{nato:[0,0],deutsch:[0,0]},e:{nato:{},deutsch:{}},x:0};let T={m:'nato',src:'all',q:[],i:0,c:0,a:0,done:false,repeat:false},E={m:'nato',q:[],i:0,c:0,w:0,done:false};
const $=x=>document.getElementById(x),sh=a=>[...a].sort(()=>Math.random()-.5),n=x=>String(x).trim().toLowerCase().replaceAll('‐','-');const ok=(a,b)=>n(a)===n(b)||(n(b)==='x-ray'&&n(a)==='xray');
function save(){localStorage.setItem(K,JSON.stringify(S))}function acc(m){return S.a[m][0]?Math.round(S.a[m][1]/S.a[m][0]*100):0}
function page(p){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('on',x.id===p));document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('on',x.dataset.page===p));if(p==='learn')learn();if(p==='stats')stats();if(p==='home')home()}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>page(b.dataset.page));$('menu').onclick=()=>$('nav').classList.toggle('open');
function learn(){let m=document.querySelector('[data-learn].active')?.dataset.learn||'nato';$('grid').innerHTML=D[m].map(x=>`<div><b>${x[0]}</b><span>${x[1]}</span></div>`).join('')}
document.querySelectorAll('[data-learn]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-learn]').forEach(x=>x.classList.remove('active'));b.classList.add('active');learn()});
function startTrain(src='all'){T.src=src;T.q=src==='errors'?Object.keys(S.e[T.m]).map(l=>D[T.m].find(x=>x[0]===l)).filter(Boolean):sh(D[T.m]);T.i=T.c=T.a=0;T.done=false;T.repeat=false;$('tm').textContent=(T.m==='nato'?'NATO':'Deutsches')+' Training';$('badge').textContent=src==='errors'?'FEHLER LERNEN · '+(T.m==='nato'?'NATO-ALPHABET':'DEUTSCHES ALPHABET'):'FEHLER LERNEN';$('badge').classList.toggle('hide',src!=='errors');$('all').classList.toggle('active',src==='all');$('errors').classList.toggle('active',src==='errors');showT()}
function showT(){if(!T.q.length){$('letter').textContent='✓';$('tp').textContent='ABGESCHLOSSEN';$('tf').className='feedback correct';$('tf').textContent='Keine offenen Fehler.';return}if(T.i>=T.q.length){$('letter').textContent='✓';$('tp').textContent='ABGESCHLOSSEN';$('tf').className='feedback correct';$('tf').textContent='Training abgeschlossen.';$('tnext').classList.add('hide');return}T.done=false;$('letter').textContent=T.q[T.i][0];$('tp').textContent=`${T.i+1} / ${T.q.length}`;$('tc').textContent=T.c;$('ta').textContent=T.a;$('tin').value='';$('tin').disabled=false;$('tcheck').disabled=false;$('tf').className='feedback hide';$('tnext').classList.add('hide');$('tin').focus()}
function submitT(){if(T.done||!T.q[T.i])return;let [l,w]=T.q[T.i],good=ok($('tin').value,w);T.done=true;T.a++;S.a[T.m][0]++;if(good){T.c++;S.a[T.m][1]++;if(T.src==='errors'){let e=S.e[T.m][l];e.streak=(e.streak||0)+1;T.repeat=e.streak<3;if(e.streak>=3){delete S.e[T.m][l];T.repeat=false}}else{T.repeat=false}}else{if(T.src==='errors'){S.e[T.m][l]??={streak:0};S.e[T.m][l].streak=0;T.repeat=true}else{S.e[T.m][l]??={streak:0};S.e[T.m][l].streak=0;T.repeat=false}}$('tf').className='feedback '+(good?'correct':'wrong');$('tf').textContent=good?`Richtig! ${l} = ${w}${T.src==='errors'&&T.repeat?' · Noch '+(3-S.e[T.m][l].streak)+'× richtig nötig':''}`:`Falsch. ${l} = ${w}${T.src==='errors'?' · Dieser Buchstabe startet wieder bei 0/3':''}`;$('tin').disabled=true;$('tcheck').disabled=true;$('tnext').classList.remove('hide');save();home();stats()}
$('tcheck').onclick=submitT;$('tnext').onclick=()=>{if(T.repeat){showT()}else{T.i++;showT()}};document.querySelectorAll('[data-train]').forEach(b=>b.onclick=()=>{T.m=b.dataset.train;document.querySelectorAll('[data-train]').forEach(x=>x.classList.toggle('active',x===b));startTrain(T.src)});$('all').onclick=()=>startTrain('all');$('errors').onclick=()=>startTrain('errors');
function startE(){E.m=$('em').value;let z=sh(D[E.m]),c=$('ec').value;E.q=z.slice(0,c==='all'?z.length:+c);E.i=E.c=E.w=0;E.done=false;$('setup').classList.add('hide');$('result').classList.add('hide');$('examarea').classList.remove('hide');showE()}
function showE(){if(E.i>=E.q.length)return finishE();E.done=false;$('eq').textContent=E.q[E.i][0];$('ep').textContent=`${E.i+1} / ${E.q.length}`;$('ein').value='';$('ein').disabled=false;$('echeck').disabled=false;$('ef').className='feedback hide';$('enext').classList.add('hide');$('ein').focus()}
function submitE(){if(E.done)return;let[l,w]=E.q[E.i],good=ok($('ein').value,w);E.done=true;S.a[E.m][0]++;if(good){E.c++;S.a[E.m][1]++}else{E.w++;S.e[E.m][l]??={streak:0};S.e[E.m][l].streak=0}$('ef').className='feedback '+(good?'correct':'wrong');$('ef').textContent=good?`Richtig! ${l} = ${w}`:`Falsch. ${l} = ${w} · Fehler gespeichert`;$('ein').disabled=true;$('echeck').disabled=true;$('enext').classList.remove('hide');save()}
$('start').onclick=startE;$('echeck').onclick=submitE;$('enext').onclick=()=>{E.i++;showE()};
document.addEventListener('keydown',e=>{if(e.key!=='Enter')return;let p=document.querySelector('.page.on')?.id;if(p==='training'){e.preventDefault();if(T.done){if(T.repeat){showT()}else{T.i++;showT()}}else if(document.activeElement===$('tin')||!$('tin').disabled){submitT()}}else if(p==='exam'&&!$('examarea').classList.contains('hide')){e.preventDefault();if(E.done){E.i++;showE()}else if(document.activeElement===$('ein')||!$('ein').disabled){submitE()}}});
function finishE(){E.done=true;S.x++;save();$('examarea').classList.add('hide');$('result').classList.remove('hide');$('percent').textContent=Math.round(E.c/E.q.length*100)+'%';$('resulttext').textContent=`${E.c} von ${E.q.length} richtig · ${E.w} Fehler`;$('errtrain').classList.toggle('hide',!E.w);home();stats()}
$('again').onclick=()=>{$('setup').classList.remove('hide');$('result').classList.add('hide')};$('errtrain').onclick=()=>{T.m=E.m;page('training');startTrain('errors')};
function home(){$('ha').textContent=acc('nato')+'%';$('hd').textContent=acc('deutsch')+'%';$('he').textContent=Object.keys(S.e.nato).length+Object.keys(S.e.deutsch).length;$('hx').textContent=S.x}
function stats(){home();$('sa').textContent=acc('nato')+'%';$('sd').textContent=acc('deutsch')+'%';$('sx').textContent=S.x;$('se').textContent=$('he').textContent;let a=['nato','deutsch'].flatMap(m=>Object.entries(S.e[m]).map(([l,e])=>`<p>${m==='nato'?'NATO':'Deutsch'}: <b>${l}</b> = ${D[m].find(x=>x[0]===l)?.[1]||''} · ${e.streak||0}/3</p>`));$('elist').innerHTML=a.length?a.join(''):'<span style="color:var(--m)">Keine offenen Fehler.</span>'}
learn();home();stats();startTrain();